/**
 * TypeScript types matching backend Pydantic schemas.
 *
 * Hand-written initially; will be auto-generated by pydantic2ts
 * in Phase 7 and CI-validated thereafter.
 */

// ── Diagnosis Report ─────────────────────────────────────────────

export interface DiagnosisReport {
  primary_category: string;
  root_cause: string;
  affected_file: string | null;
  affected_line: number | null;
  fix_suggestion: string;
  confidence: number; // 0.0 – 1.0
  early_stopped: boolean;
  evidence_chain: EvidenceRef[];
  raw_refs: string[];
  notes: string | null;
}

export interface EvidenceRef {
  signal_id: string;
  finding_id: string;
  description: string;
}

// ── Budget ───────────────────────────────────────────────────────

export interface BudgetState {
  iteration: number;
  max_iterations: number;
  tool_calls: number;
  max_tool_calls: number;
  total_tokens: number;
  max_tokens: number;
  total_cost_usd: number;
  usage_ratio: number; // 0.0 – 1.0
  phase: string;
  elapsed_seconds: number;
  early_stopped: boolean;
}

export interface BudgetTick {
  iteration: number;
  tool_calls: number;
  total_tokens: number;
  total_cost_usd: number;
  phase: string;
  elapsed_seconds: number;
  timestamp: string; // ISO-8601
}

// ── Evidence ─────────────────────────────────────────────────────

export interface NormalizedEvidence {
  golden_signals: Signal[];
  correlations: Correlation[];
  timeline: TimelineEvent[];
  evidence: Evidence[];
}

export interface Signal {
  id: string;
  source: "loki" | "tempo" | "frontend" | "database" | "code";
  type: string;
  value: string;
  severity: "critical" | "error" | "warning" | "info";
  timestamp: string | null;
  metadata: Record<string, unknown>;
}

export interface Correlation {
  id: string;
  signal_ids: string[];
  description: string;
  confidence: number;
}

export interface TimelineEvent {
  timestamp: string;
  source: string;
  event_type: string;
  message: string;
  trace_id: string | null;
  span_id: string | null;
}

export interface Evidence {
  id: string;
  type: string;
  content: string;
  source: string;
  timestamp: string | null;
}

// ── Findings ─────────────────────────────────────────────────────

export interface Finding {
  id: string;
  description: string;
  confidence: number;
  evidence_refs: string[];
  category: string;
}

// ── Cases & Runs (eval) ──────────────────────────────────────────

export interface CaseItem {
  recipe_id: string;
  title: string;
  category: string;
  categories: string[];
  split: "train" | "test";
  difficulty: "easy" | "medium" | "hard";
  severity: "low" | "medium" | "high" | "critical";
  expected_diagnosis: DiagnosisReport;
}

export interface RunSummary {
  run_name: string;
  case_count: number;
  created_at: string;
}

export interface ScoreSummary {
  recipe_id: string;
  scores: Record<string, number>; // 9 dimensions
  overall: number;
  trace_id: string;
  trace_url: string;
}

// ── Feedback ─────────────────────────────────────────────────────

export interface FeedbackRequest {
  trace_id: string;
  recipe_id: string;
  run_name: string | null;
  corrected_field: string;
  value: string;
  note: string | null;
}

export interface FeedbackResponse {
  status: string;
  feedback_id: string;
}

// ── Diagnose API response (non-streaming, for benchmark) ─────────

export interface DiagnoseResponse {
  report: DiagnosisReport;
  findings_count: number;
  budget: BudgetState;
  evidence: NormalizedEvidence;
  correlations: Correlation[];
  timeline: TimelineEvent[];
}
