/**
 * TypeScript types matching backend Pydantic schemas (doctor/backend/src/graph/state.py).
 *
 * Hand-written initially; will be auto-generated by pydantic2ts
 * in Phase 7 and CI-validated thereafter.
 *
 * ⚠️ Keep field names in sync with the backend Pydantic models:
 *   Signal, Correlation, TimelineEvent, NormalizedEvidence, Finding,
 *   DiagnosisReport, BudgetState, Evidence (raw input).
 */

// ── Diagnosis Report ─────────────────────────────────────────────

export type BugCategory =
  | "frontend_crash"
  | "backend_error"
  | "performance"
  | "logic"
  | "data"
  | "config";

export type ServiceTier = "frontend" | "backend";
export type RootCauseTier = "frontend" | "backend" | "data";

export interface DiagnosisReport {
  primary_category: string;
  categories: string[];
  symptom_tier: ServiceTier;
  root_cause_tier: RootCauseTier;
  root_cause: string;
  affected_file: string | null;
  affected_line: number | null;
  fix_suggestion: string;
  /** Ordered chain of evidence_ref strings grounding the root cause. */
  evidence_chain: string[];
  confidence: number; // 0.0 – 1.0
  early_stopped: boolean;
  notes: string;
}

// ── Budget ───────────────────────────────────────────────────────

export interface BudgetState {
  total_tokens: number;
  total_cost_usd: number;
  tool_calls: number;
  started_at: string | null;
  elapsed_seconds: number;
  last_checked_at: string | null;
}

/**
 * Incremental budget snapshot appended before each LLM call by
 * BudgetGuardMiddleware. Field set is a superset of BudgetState;
 * optional because the middleware dict is free-form.
 */
export interface BudgetTick {
  iteration?: number;
  tool_calls?: number;
  total_tokens?: number;
  total_cost_usd?: number;
  phase?: string;
  elapsed_seconds?: number;
  model_call_count?: number;
  budget_exhausted?: boolean;
}

// ── Normalized Evidence (Ingest layer output) ────────────────────

export type SignalSource =
  | "log"
  | "trace"
  | "browser_error"
  | "api_response"
  | "user_report";

export type SignalType =
  | "error_log"
  | "error_span"
  | "slow_span"
  | "repeated_query"
  | "behavior_mismatch"
  | "data_invariant_broken"
  | "access_control_anomaly"
  | "silent_data_loss";

export type SignalSeverity = "error" | "warning" | "info";

export interface Signal {
  signal_id: string;
  source: SignalSource;
  signal_type: SignalType;
  service_tier: ServiceTier;
  severity: SignalSeverity;
  summary: string;
  /** Reference ID back to the raw evidence (used as graph edge key). */
  evidence_ref: string;
  timestamp: string | null;
  metadata: Record<string, unknown>;
}

export type TimelineSource = "log" | "trace" | "browser_error" | "api";

export interface TimelineEvent {
  timestamp: string;
  source: TimelineSource;
  service_tier: ServiceTier;
  service_name: string;
  description: string;
  evidence_ref: string;
  trace_id: string | null;
}

export interface Correlation {
  correlation_id: string;
  trace_id: string | null;
  description: string;
  frontend_signals: string[]; // signal_ids
  backend_signals: string[];
  db_signals: string[];
  confidence: number; // 0.0 – 1.0
}

export interface NormalizedEvidence {
  user_report: string;
  golden_signals: Signal[];
  timeline: TimelineEvent[];
  correlations: Correlation[];
  /** Index from evidence_ref → raw evidence payload. */
  raw_refs: Record<string, unknown>;
  noise_ratio: number; // 0.0 – 1.0
  trigger_time: string | null;
  trigger_trace_ids: string[];
  frontend_span_count: number;
  backend_span_count: number;
  metadata: Record<string, unknown>;
}

// ── Findings ─────────────────────────────────────────────────────

export interface Finding {
  agent: string;
  summary: string;
  evidence_refs: string[];
  affected_files: string[];
  fix_suggestion: string;
  confidence: number; // 0.0 – 1.0
  cross_layer: boolean;
  contradiction: boolean;
}

// ── Raw evidence input (user-facing request body) ────────────────

export interface LogEntry {
  timestamp: string;
  level: string;
  service: string;
  service_name: string;
  message: string;
  trace_id: string | null;
  span_id: string | null;
  attributes: Record<string, unknown>;
}

export interface TraceSpan {
  trace_id: string;
  span_id: string;
  parent_span_id: string;
  name: string;
  service: string;
  service_name: string;
  start: string;
  duration_ms: number;
  attributes: Record<string, unknown>;
  status: "ok" | "error" | "unset";
  db_statement: string;
}

export interface BrowserError {
  message: string;
  source: string;
  lineno: number;
  colno: number;
  stack: string;
  trace_id: string | null;
  span_id: string | null;
  component_stack: string;
  breadcrumbs: Record<string, unknown>[];
  timestamp: string;
}

export interface Evidence {
  user_report: string;
  logs: LogEntry[];
  traces: TraceSpan[];
  browser_errors: BrowserError[];
  error_screenshot_url: string | null;
  request: Record<string, unknown> | null;
  response: Record<string, unknown> | null;
  trigger_time: string | null;
  trigger_trace_ids: string[];
}

// ── Diagnose API response (non-streaming, for benchmark) ─────────

export interface DiagnoseResponse {
  thread_id: string;
  report: DiagnosisReport | null;
  primary_category: string | null;
  categories: string[];
  findings_count: number;
  budget: BudgetState | null;
  findings: Finding[];
  evidence: NormalizedEvidence | null;
  correlations: Correlation[];
  timeline: TimelineEvent[];
}

// ── SSE events (streaming mode, ?stream=true) ────────────────────

export interface SSEChatModelEvent {
  event: "on_chat_model_start" | "on_chat_model_stream" | "on_chat_model_end";
  name: string;
  data: Record<string, unknown>;
}

export interface SSEReportEvent {
  event: "report";
  report: DiagnosisReport;
}

/** Final event carrying the full evidence-chain payload (Phase 2). */
export interface SSEFinalEvent {
  event: "final";
  report: DiagnosisReport | null;
  budget: BudgetState | null;
  findings: Finding[];
  evidence: NormalizedEvidence | null;
  correlations: Correlation[];
  timeline: TimelineEvent[];
}

export interface SSEErrorEvent {
  event: "error";
  message: string;
}

export type SSEEvent = SSEChatModelEvent | SSEReportEvent | SSEFinalEvent | SSEErrorEvent;

// ── Cases & Runs (eval) ──────────────────────────────────────────

export interface CaseItem {
  recipe_id: string;
  title: string;
  category: string;
  categories: string[];
  split: "train" | "test";
  difficulty: "easy" | "medium" | "hard";
  severity: "low" | "medium" | "high" | "critical";
  expected_diagnosis: DiagnosisReport;
}

export interface RunSummary {
  run_name: string;
  case_count: number;
  created_at: string;
}

export interface ScoreSummary {
  recipe_id: string;
  scores: Record<string, number>; // 9 dimensions
  overall: number;
  trace_id: string;
  trace_url: string;
}

// ── Feedback ─────────────────────────────────────────────────────

export interface FeedbackRequest {
  trace_id: string;
  recipe_id: string;
  run_name: string | null;
  corrected_field: string;
  value: string;
  note: string | null;
}

export interface FeedbackResponse {
  status: string;
  feedback_id: string;
}
