"""Bug Factory — Bug generation and injection for DiagDoctor."""

from bug_factory.ai_rewriter import (
    AIRewriter,
    DiffPatchApplier,
    PatchError,
    RewriteError,
    detect_language,
    extract_code_block,
)
from bug_factory.git_manager import GitManager, GitOperationError
from bug_factory.injector import BugInjector
from bug_factory.schema import (
    BrowserError,
    BugRecipe,
    CollectedEvidence,
    Evaluation,
    ExpectedDiagnosis,
    ExpectedObservation,
    Injection,
    InjectionError,
    InjectionResult,
    LogEntry,
    LogPattern,
    StepResult,
    TraceSpan,
    Trigger,
    TriggerError,
    TriggerResult,
    TriggerStep,
    load_recipe,
    validate_all_recipes,
)

__all__ = [
    "AIRewriter",
    "BrowserError",
    "BugInjector",
    "CollectedEvidence",
    "DiffPatchApplier",
    "GitManager",
    "GitOperationError",
    "InjectionError",
    "InjectionResult",
    "LogEntry",
    "PatchError",
    "RewriteError",
    "TraceSpan",
    "detect_language",
    "extract_code_block",
    "BugRecipe",
    "ExpectedDiagnosis",
    "ExpectedObservation",
    "Evaluation",
    "Injection",
    "LogPattern",
    "StepResult",
    "Trigger",
    "TriggerError",
    "TriggerResult",
    "TriggerStep",
    "load_recipe",
    "validate_all_recipes",
]
