allowBuilds:
  '@scarf/scarf': false
minimumReleaseAgeExclude:
  - '@copilotkit/a2ui-renderer@1.65.0'
  - '@copilotkit/core@1.65.0'
  - '@copilotkit/react-core@1.65.0'
  - '@copilotkit/react-ui@1.65.0'
  - '@copilotkit/runtime-client-gql@1.65.0'
  - '@copilotkit/shared@1.65.0'
  - '@copilotkit/web-components@1.65.0'
  - '@copilotkit/web-inspector@1.65.0'
