"""Alembic migrations script template."""

revision = "eb6e0ac33663"
down_revision = "e8e3f9ebff95"
branch_labels = None
depends_on = None


from alembic import op


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "projects", "users", ["owner_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    # ### end Alembic commands ###
